name: "lint-unit testing"

on: [push, pull_request]

jobs:
  lint-unit-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare Node modules
        run: npm ci

      - name: Check Lint
        run: npm run lint

      - name: Run test cases
        run: npm run test